#!/bin/bash

# COMP2137 - System Information Report Script
# Author: Makayla Cuneo
# Date: 10/8/2025

# Store evaluated command output in variables
hostname=$(hostname)
username=$(whoami)
datetime=$(date)

source /etc/os-release
os="$NAME $VERSION"

uptime=$(uptime -p)

cpu=$(lshw -class processor 2>/dev/null | grep -m 1 'product:' | cut -d: -f2 | xargs)

ram=$(free -h | awk '/Mem:/ {print $2}')

disks=$(lshw -class disk 2>/dev/null | awk '/product:|size:/' | paste - - | sed 's/product:/Disk:/; s/size:/Size:/')

video=$(lshw -class display 2>/dev/null | grep 'product:' | cut -d: -f2 | xargs)

gateway=$(ip route | awk '/default/ {print $3}')
interface=$(ip route | awk '/default/ {print $5}')
host_ip=$(ip -4 addr show "$interface" | awk '/inet / {print $2}' | cut -d/ -f1)

dns=$(grep nameserver /etc/resolv.conf | head -n 1 | awk '{print $2}')

# System status
users=$(who | awk '{print $1}' | sort | uniq | paste -sd "," -)

diskspace=$(df -h --output=target,avail | tail -n +2 | awk '{print $1 " " $2}' | paste -sd ", " -)

processes=$(ps -e --no-headers | wc -l)

loadavg=$(uptime | awk -F'load average:' '{print $2}' | xargs)

# Get all listening ports (TCP/UDP), remove duplicates, and join with commas
ports=$(ss -tuln | awk 'NR>1 {split($5, a, ":"); print a[length(a)]}' | sort -n | uniq | paste -sd,)

echo "Listening Network Ports: $ports"

if command -v ufw >/dev/null 2>&1; then
    ufw_status=$(sudo ufw status | head -n 1)
    echo "UFW Status: $ufw_status"
else
    echo "UFW Status: UFW not installed"
fi

# Output the report
echo ""
cat <<EOF
System Report for $hostname generated by $username, on $datetime

System Information
------------------
OS: $os
Uptime: $uptime
CPU: $cpu
RAM: $ram
Disk(s): $disks
Video: $video
Host Address: $host_ip
Gateway IP: $gateway
DNS Server: $dns

System Status
-------------
Users Logged In: $users
Disk Space: $diskspace
Process Count: $processes
Load Averages: $loadavg
Listening Network Ports: $ports
UFW Status: $ufw_status
EOF
echo ""

