#!/bin/bash

# Gather system data
HOSTNAME=$(hostname)
USERNAME=$(whoami)
DATETIME=$(date)

source /etc/os-release
OS="$NAME $VERSION"

UPTIME=$(uptime -p)

CPU=$(lshw -class processor | grep -m 1 'product:' | awk -F: '{print $2}' | xargs)

RAM=$(free -h | awk '/Mem:/ {print $2}')

DISKS=$(lshw -class disk | awk '/product:|size:/' | paste - - | sed 's/product:/Disk:/; s/size:/Size:/')

VIDEO=$(lshw -class display | grep 'product:' | awk -F: '{print $2}' | xargs)

GATEWAY=$(ip r | grep default | awk '{print $3}')
INTERFACE=$(ip r | grep default | awk '{print $5}')
HOSTADDR=$(ip -4 a show $INTERFACE | grep inet | awk '{print $2}' | cut -d/ -f1)

DNS=$(grep "nameserver" /etc/resolv.conf | head -n 1 | awk '{print $2}')

# System status
USERS=$(who | awk '{print $1}' | sort | uniq | paste -sd "," -)

DISKSPACE=$(df -h --output=target,avail | tail -n +2 | awk '{print $1 " " $2}' | paste -sd ", " -)

PROCESSCOUNT=$(ps aux | wc -l)

LOADAVG=$(uptime | awk -F'load average:' '{print $2}' | xargs)

PORTS=$(ss -tuln | awk 'NR>1 {split($5,a,":"); for (i in a) if (a[i] ~ /^[0-9]+$/) print a[i]}' | sort -n | uniq | paste -sd ", " -)

UFWSTATUS=$(ufw status | head -n 1)

# Output report
echo ""
cat <<EOF
System Report for $HOSTNAME generated by $USERNAME, on $DATETIME

System Information
------------------
OS: $OS
Uptime: $UPTIME
CPU: $CPU
RAM: $RAM
Disk(s): $DISKS
Video: $VIDEO
Host Address: $HOSTADDR
Gateway IP: $GATEWAY
DNS Server: $DNS

System Status
-------------
Users Logged In: $USERS
Disk Space: $DISKSPACE
Process Count: $PROCESSCOUNT
Load Averages: $LOADAVG
Listening Network Ports: $PORTS
UFW Status: $UFWSTATUS
EOF
echo ""

