#!/bin/bash

# COMP2137 - System Information Report Script
# Author: Makayla Cuneo
# Date: 10/8/2025
#Line for clean output
echo ""
# Storing of evaluated variables
hostname=$(hostname)
username=$USER
datetime=$(date)
#OS version command
source /etc/os-release
os="$NAME $VERSION"
#Uptime cmd
uptime=$(uptime -p)
#CPU cmd
cpu=$(grep -m 1 "model name" /proc/cpuinfo | cut -d: -f2)
#RAM cmd
ram=$(free -h | awk '/Mem:/ {print $2}')
#Disks
disks=$(lshw -class disk 2>/dev/null | awk '/product:|size:/' | paste - - | sed 's/product:/Disk:/; s/size:/Size:/')
#Video
video=$(lspci | grep -m 1 VGA | cut -d: -f3 | sed 's/^ *//')
#IP 
gateway=$(ip route | awk '/default/ {print $3}')
interface=$(ip route | awk '/default/ {print $5}')
host_ip=$(ip -4 addr show "$interface" | awk '/inet / {print $2}' | cut -d/ -f1)
#DNS
dns=$(grep nameserver /etc/resolv.conf | head -n 1 | awk '{print $2}')

# System status
users=$(who | awk '{print $1}' | sort | uniq | paste -sd "," -)
#Amount of diskspace
diskspace=$(df -h --output=target,avail | tail -n +2 | awk '{print $1 " " $2}' | paste -sd ", " -)
#Processes Ran
processes=$(ps -e --no-headers | wc -l)
#Load average
loadavg=$(uptime | cut -d':' -f2)

# Show all listenig ports (TCP/UDP) and do not show duplcates
ports=$(ss -tuln | awk 'NR>1 {split($5, a, ":"); print a[length(a)]}' | sort -n | uniq | paste -sd,)

#UFW Status
ufw_status=$(ufw status 2>/dev/null | grep -m 1 "Status:" || echo "UFW not available or inactive")


# Printed output of report
echo ""
cat <<EOF
System Report for $hostname generated by $username, on $datetime

System Information
------------------
OS: $os
Uptime: $uptime
CPU: $cpu
RAM: $ram
Disk(s): $disks
Video: $video
Host Address: $host_ip
Gateway IP: $gateway
DNS Server: $dns

System Status
-------------
Users Logged In: $users
Disk Space: $diskspace
Process Count: $processes
Load Averages: $loadavg
Listening Network Ports: $ports
UFW Status: $ufw_status
EOF
echo ""

